services:
  rescue-api-rest:
    build: .
    image: api/rescue:v1
    ports:
      - "8000:8000"
    environment:
      - DOCKER=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rescue
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MERCADO_PAGO_ACCESS_TOKEN=APP_USR-4993987139809199-100718-6cf7e47324c3edfb890bc7aaf6e29808-2013334309
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rescue
      
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rescue" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
