name: Tests
on:
  push:
    branches: [ main, master, development ]
  pull_request:
    branches: [ main, master, development ]
jobs:
  test:
    environment: 
     - name: environments 
     - secrets: 
       - FIREBASE_API_KEY
       - FIREBASE_DOMAIN
       - FIREBASE_PROJECT_ID
       - FIREBASE_STORAGE_BUCKET
       - FIREBASE_MESSAGE_ID
       - FIREBASE_APP_ID
       - FIREBASE_MEASUREMENT_ID
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - run: npm ci
    - name: Run tests
      run: npm test